FROM python:3.11-slim-bookworm
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
COPY interface.py .
CMD ["uvicorn", "interface:app", "--host", "0.0.0.0", "--port", "8080"]
